### ISSUE TITLE
cuda-strides  complier error

### ISSUE THREAD

**Issue by villanel** [te42kyfo/gpu-benches#5]
nvcc -std=c++17 -O3 -arch=sm_70 --compiler-options="-O2 -pipe -Wall -fopenmp -g" -Xcompiler -rdynamic --generate-line-info  -Xcompiler \"-Wl,-rpath,/usr/local/cuda/extras/CUPTI/lib64/\" -Xcompiler "-Wall" -I/usr/local/cuda/extras/CUPTI/include -o cuda-strides main.cu -L/usr/local/cuda/lib64 -L/usr/local/cuda/extras/CUPTI/lib64 -lcupti -lcuda -lnvidia-ml
../gpu-metrics/cuda_metrics/Eval.hpp(72): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(72): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(75): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(78): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(78): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(83): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(84): error: identifier "NVPW_MetricsEvaluator" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(84): error: identifier "metricEvaluator" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(96): error: identifier "NVPW_MetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(97): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(97): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(101): error: identifier "NVPW_MetricEvalRequest_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(102): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(127): error: identifier "NVPW_MetricsEvaluator_SetDeviceAttributes_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(127): error: identifier "NVPW_MetricsEvaluator_SetDeviceAttributes_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(131): error: identifier "NVPW_MetricsEvaluator_SetDeviceAttributes" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(134): error: identifier "NVPW_MetricsEvaluator_EvaluateToGpuValues_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(134): error: identifier "NVPW_MetricsEvaluator_EvaluateToGpuValues_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(139): error: identifier "NVPW_MetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(145): error: identifier "NVPW_MetricsEvaluator_EvaluateToGpuValues" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(151): error: identifier "NVPW_MetricsEvaluator_Destroy_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(151): error: identifier "NVPW_MetricsEvaluator_Destroy_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(153): error: identifier "NVPW_MetricsEvaluator_Destroy" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(168): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(168): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(171): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(174): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(174): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(181): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(182): error: identifier "NVPW_MetricsEvaluator" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(182): error: identifier "metricEvaluator" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(199): error: identifier "NVPW_MetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(200): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(200): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(204): error: identifier "NVPW_MetricEvalRequest_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(205): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(227): error: identifier "NVPW_MetricsEvaluator_SetDeviceAttributes_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(227): error: identifier "NVPW_MetricsEvaluator_SetDeviceAttributes_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(231): error: identifier "NVPW_MetricsEvaluator_SetDeviceAttributes" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(234): error: identifier "NVPW_MetricsEvaluator_EvaluateToGpuValues_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(234): error: identifier "NVPW_MetricsEvaluator_EvaluateToGpuValues_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(239): error: identifier "NVPW_MetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(245): error: identifier "NVPW_MetricsEvaluator_EvaluateToGpuValues" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(252): error: identifier "NVPW_MetricsEvaluator_Destroy_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(252): error: identifier "NVPW_MetricsEvaluator_Destroy_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(254): error: identifier "NVPW_MetricsEvaluator_Destroy" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(270): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(270): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(273): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(276): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(276): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(283): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(284): error: identifier "NVPW_MetricsEvaluator" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(284): error: identifier "metricEvaluator" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(301): error: identifier "NVPW_MetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(302): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(302): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(306): error: identifier "NVPW_MetricEvalRequest_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(307): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(329): error: identifier "NVPW_MetricsEvaluator_SetDeviceAttributes_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(329): error: identifier "NVPW_MetricsEvaluator_SetDeviceAttributes_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(333): error: identifier "NVPW_MetricsEvaluator_SetDeviceAttributes" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(336): error: identifier "NVPW_MetricsEvaluator_EvaluateToGpuValues_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(336): error: identifier "NVPW_MetricsEvaluator_EvaluateToGpuValues_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(341): error: identifier "NVPW_MetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(347): error: identifier "NVPW_MetricsEvaluator_EvaluateToGpuValues" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(355): error: identifier "NVPW_MetricsEvaluator_Destroy_Params" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(355): error: identifier "NVPW_MetricsEvaluator_Destroy_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Eval.hpp(357): error: identifier "NVPW_MetricsEvaluator_Destroy" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(17): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(17): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(20): error: identifier "NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(23): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize_Params" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(23): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(28): error: identifier "NVPW_CUDA_MetricsEvaluator_Initialize" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(29): error: identifier "NVPW_MetricsEvaluator" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(29): error: identifier "metricEvaluator" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(39): error: identifier "NVPW_MetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(40): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest_Params" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(40): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(44): error: identifier "NVPW_MetricEvalRequest_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(45): error: identifier "NVPW_MetricsEvaluator_ConvertMetricNameToMetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(48): error: identifier "NVPW_MetricsEvaluator_GetMetricRawDependencies_Params" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(48): error: identifier "NVPW_MetricsEvaluator_GetMetricRawDependencies_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(53): error: identifier "NVPW_MetricEvalRequest" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(54): error: identifier "NVPW_MetricsEvaluator_GetMetricRawDependencies" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(57): error: identifier "NVPW_MetricsEvaluator_GetMetricRawDependencies" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(74): error: identifier "NVPW_MetricsEvaluator_Destroy_Params" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(74): error: identifier "NVPW_MetricsEvaluator_Destroy_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(76): error: identifier "NVPW_MetricsEvaluator_Destroy" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(85): error: identifier "NVPW_CUDA_RawMetricsConfig_Create_V2_Params" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(85): error: identifier "NVPW_CUDA_RawMetricsConfig_Create_V2_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(89): error: identifier "NVPW_CUDA_RawMetricsConfig_Create_V2" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(141): error: identifier "NVPW_CUDA_CounterDataBuilder_Create_Params" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(141): error: identifier "NVPW_CUDA_CounterDataBuilder_Create_Params_STRUCT_SIZE" is undefined

../gpu-metrics/cuda_metrics/Metric.hpp(144): error: identifier "NVPW_CUDA_CounterDataBuilder_Create" is undefined

main.cu(167): error: identifier "measureMetricStop" is undefined

**Comment by te42kyfo** [comment]
I just pushed a new revision of this benchmark.

This benchmark still used the old metric measurement functions. There is now vendor agnostic functions in gpu-metrics.

This benchmark has also in the meantime gone trough some further developement. Note that is measures a lot of performance counters, which are very device specific. This benchmark is tested to work with A100 and MI210 GPUs.
